### ISSUE TITLE
NoMethodError - undefined method `map' for #<String:0x007ff0b51941c0>

### ISSUE THREAD

**Issue by vipul30** [WideEyeLabs/ruby-openstates#6]
The code to find Legislators (or other similiar 'where' api calls) do not seem to work anymore.  We have had this code in production for a while, but are now getting this error

NoMethodError - undefined method `map' for #<String:0x007ff0b51941c0>

openstates (0.0.1) lib/openstates/model.rb:37:in `where'

This is the how we are calling the method.
OpenStates::Legislator.where(parameters)

This is the parameters option
parameters = {:state=>"Ca"} # hash

**Comment by endoze** [comment]
Interesting. My first guess is that instead of the api returning an array like expected, it's returning a single result that's a string. That would generate a similar error.

Can you confirm for me that the api is returning a single string instead of an array?

If that's the case, I think I can handle both cases pretty transparently.

**Comment by vipul30** [comment]
I debugged some more and here's a more specific error message.

location: "https://openstates.org/api/v1/committees/?apikey=mywpikey&state=az"
"<html>\r\n<head><title>301 Moved Permanently</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>301 Moved Permanently</h1></center>\r\n<hr><center>nginx/1.10.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"

**Comment by endoze** [comment]
@vipul30 Oh that looks fun :smile:. Once I get a bit of free time, I'll dig in and see what I can do to try and help. 

In the mean time, if you discover what (if any) changes are necessary to fix this issue, please feel free to submit a pull request. I'd be happy to merge it in if it fixes an issue with this gem.

**Comment by fcfowler** [comment]
@vipul30 OpenStates is now requiring SSL. This is reflected in the updated `BASE_URL` of the code here, but the change is not reflected in the rubygems.org installation. Using the code directly from the repo fixed the issue for me:

`gem 'openstates', github: "WideEyeLabs/ruby-openstates"`

**Comment by endoze** [comment]
@fcfowler @vipul30 I'll cut a new release that includes the updated `BASE_URL`. 

I'm going to close this issue as resolved, but please feel free to reopen if this isn't the correct solution.

**Comment by vipul30** [comment]
Thank you.

**Comment by endoze** [comment]
I've released [version 0.1.0](https://rubygems.org/gems/openstates/versions/0.1.0) on ruby gems. Please let me know if this doesn't resolve your issue. @fcfowler @vipul30 Thank you both for your contributions, they are very much appreciated.

**Comment by fcfowler** [comment]
@endoze dude thank _you_. This gem saved me so much headache.. Here's the project it's being used on:

http://takeaction.i4qed.org/

**Comment by endoze** [comment]
@fcfowler Feel free to open a pull request adding a 'popular projects using this gem' type thing adding a reference to your project in the `README.md`. It makes me glad that this gem is being used for something pretty cool.

Thanks again for your contributions!
